### ISSUE TITLE
Unable to install marconibot

### ISSUE THREAD

**Issue by LeonidShamis** [s4w3d0ff/marconibot#47]
Hi,

I've tried to install marconibot in a virtualenv (`pip install git+https://github.com/s4w3d0ff/marconibot.git`) but I'm getting the error shown below.
Is there another way to install this bot?

(marconibot) C:\Users\LEONIDS\Envs\marconibot>python --version
Python 3.6.1

(marconibot) C:\Users\LEONIDS\Envs\marconibot>pip --version
pip 9.0.1 from c:\users\leonids\envs\marconibot\lib\site-packages (python 3.6)

(marconibot) C:\Users\LEONIDS\Envs\marconibot>pip install git+https://github.com/s4w3d0ff/marconibot.git
Collecting git+https://github.com/s4w3d0ff/marconibot.git
  Cloning https://github.com/s4w3d0ff/marconibot.git to c:\users\leonids\appdata\local\temp\pip-qgfsuybe-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LEONIDS\AppData\Local\Temp\pip-qgfsuybe-build\setup.py", line 2, in <module>
        from marconi import __version__
      File "C:\Users\LEONIDS\AppData\Local\Temp\pip-qgfsuybe-build\marconi\__init__.py", line 2, in <module>
        import tools
    ModuleNotFoundError: No module named 'tools'

Command "python setup.py egg_info" failed with error code 1 in C:\Users\LEONIDS\AppData\Local\Temp\pip-qgfsuybe-build\

(marconibot) C:\Users\LEONIDS\Envs\marconibot>

**Comment by s4w3d0ff** [comment]
Ya, the package structure is fubar right now. Expect huge structure changes in the future. For now, most of the inner modules work fine if you work directly from the marconibot/marconi dir.

But yes, the setup.py and overall structure of this repo needs improvement/refining.  

Keep in mind this isn't a 'working' bot (I plan on having it fully functional), but for now it is just a series of tools that would come in handy when creating a poloniex trade bot. I'll create a release once this repo becomes more 'mature'. But, for now, the easiest way to use this repo is to clone it and copy the marconi dir into your project.

**Comment by LeonidShamis** [comment]
Hi,

Thank you for the prompt response.
I've cloned the repo (c:\Users\LEONIDS\Envs\marconibot\marconi) and installed the required packages dependencies manually:

```
(marconibot) C:\Users\LEONIDS\Envs\marconibot>pip install requests numpy bokeh cherrypy beautifulsoup4 pymongo pandas websocket-client
...
(marconibot) C:\Users\LEONIDS\Envs\marconibot>pip install git+https://git@github.com/s4w3d0ff/python-poloniex.git
...
```

However, there is still some issue with importing some other modules as shown below.
I'm not sure if there is an alternative way to try running this project:

```
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>python ticker.py
Traceback (most recent call last):
  File "ticker.py", line 3, in <module>
    from tools import MongoClient, websocket
  File "C:\Users\LEONIDS\Envs\marconibot\marconi\tools\__init__.py", line 35, in <module>
    from .daemon import DaemonContext
  File "C:\Users\LEONIDS\Envs\marconibot\marconi\tools\daemon\__init__.py", line 42, in <module>
    from .daemon import DaemonContext
  File "C:\Users\LEONIDS\Envs\marconibot\marconi\tools\daemon\daemon.py", line 26, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>
```

**Comment by s4w3d0ff** [comment]
Seems like the daemonizing module i was planning to use has issues with windows.

No packages depend on the module yet so you can comment out that line (`from .daemon import DaemonContext`) and it shouldn't be an issue.

Make sure you have the dependencies installed, current dependencies are:
```
pip3 install numpy scikit-learn bokeh cherrypy beautifulsoup4 pymongo pandas websocket-client
pip3 install git+https://github.com/s4w3d0ff/python-poloniex.git
``` 
Edit: derp, just saw that you installed the dependencies manually, you will probably need scikit-learn as well.

**Comment by LeonidShamis** [comment]
Yes, I already had those dependencies installed manually.
I've followed your advice and commented out `from .daemon import DaemonContext` line in `marconi\tools\__init__.py` file.

That wasn't enough - the following packages (dependencies) needed to be added:
* sklearn
* scipy (I used http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy)
* numpy+mkl (I used http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)

After pip installing the above, there was one more issue:
```
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>python ticker.py
Traceback (most recent call last):
  File "ticker.py", line 3, in <module>
    from tools import MongoClient, websocket
ImportError: cannot import name 'MongoClient'
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>python ticker.py
```
I ended up explicitly importing `MongoClient` in `marconi\tools\__init__.py` by adding `from pymongo import MongoClient` line.

Here is the output:
```
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>python ticker.py
INFO:__main__:Thread started
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
None
DEBUG:urllib3.connectionpool:https://poloniex.com:443 "GET /public?command=returnTicker HTTP/1.1" 200 None
INFO:__main__:Populated markets database with ticker data
INFO:__main__:Subscribed to ticker
{'_id': 'USDT_BTC',
 'baseVolume': '13969720.67200998',
 'high24hr': '2605.44380335',
 'highestBid': '2596.40000000',
 'id': 121.0,
 'isFrozen': '0',
 'last': '2596.40793175',
 'low24hr': '2546.38790528',
 'lowestAsk': '2596.40793175',
 'percentChange': '-0.00291554',
 'quoteVolume': '5416.90700607'}
{'_id': 'USDT_BTC',
 'baseVolume': '13969720.67200998',
 'high24hr': '2605.44380335',
 'highestBid': '2596.40000000',
 'id': 121.0,
 'isFrozen': '0',
 'last': '2596.40793175',
 'low24hr': '2546.38790528',
 'lowestAsk': '2596.40793175',
 'percentChange': '-0.00291554',
 'quoteVolume': '5416.90700607'}
INFO:__main__:Websocket closed!
INFO:__main__:Thread joined
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>
```

```
(marconibot) C:\Users\LEONIDS\Envs\marconibot\marconi>mongo
> use poloniex
switched to db poloniex
> db.ticker.find().count()
90
>
```

Thank you!

**Comment by s4w3d0ff** [comment]
The module and packages should be easier to install now, I still find bugs when installing on some systems but they seem easy enough to work through. 

It is usually a SciPy issue with pip.
